name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: course-checker:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        # Start the container in detached mode
        docker run -d --name test-container -p 3000:3000 course-checker:latest
        
        # Wait for the application to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:3000/api/health || exit 1
        
        # Clean up
        docker stop test-container
        docker rm test-container

    - name: Run security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'course-checker:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'